// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Race = { id: number, runner: number, name: string, eventDate: string, isDeleted: boolean, createdAt: string, updatedAt: string, };
