// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RaceListRace = { id: bigint, runner: bigint, name: string, event_date: string, is_deleted: boolean, runner_name: string, };
