CREATE TABLE IF NOT EXISTS aid_stations (
  id INTEGER PRIMARY KEY NOT NULL,
  race_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  distance_km REAL NOT NULL,
  is_crew_allowed BOOLEAN DEFAULT FALSE NOT NULL,
  has_drop_bag BOOLEAN DEFAULT FALSE NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  arrival_timestamp INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

  FOREIGN KEY (race_id) REFERENCES races (id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS aid_station_checklist_items (
  id INTEGER PRIMARY KEY NOT NULL,
  aid_station_id INTEGER NOT NULL,
  item TEXT NOT NULL,
  checked BOOLEAN DEFAULT FALSE NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

  FOREIGN KEY (aid_station_id) REFERENCES aid_stations (id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS routes (
  id INTEGER PRIMARY KEY NOT NULL,
  race_id INTEGER NOT NULL,
  total_distance_km REAL NOT NULL,
  total_elevation_gain_m REAL NOT NULL,
  total_elevation_loss_m REAL NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

  FOREIGN KEY (race_id) REFERENCES races (id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS route_segments (
  id INTEGER PRIMARY KEY NOT NULL,
  route_id INTEGER NOT NULL,
  km REAL NOT NULL,
  gain_m REAL NOT NULL,
  loss_m REAL NOT NULL,

  FOREIGN KEY (route_id) REFERENCES routes (id)
    ON DELETE CASCADE
);
