CREATE TABLE IF NOT EXISTS races (
  id INTEGER PRIMARY KEY NOT NULL,
  runner INTEGER NOT NULL,
  name TEXT NOT NULL,
  event_date DATE NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

  FOREIGN KEY (runner) REFERENCES users (id)
    ON DELETE CASCADE
);
